SELECT 
	TABLE_CATALOG,
	TABLE_NAME,
	TABLE_SCHEMA,
	TABLE_TYPE,
	CASE TABLE_SCHEMA 
		WHEN 'bronze' THEN 1
		WHEN 'silver' THEN 2
		WHEN 'gold' THEN 3
	END AS RANK
FROM INFORMATION_SCHEMA.TABLES
ORDER BY RANK