--Total customers by countries
SELECT
	country,
	COUNT(*) AS total_number_of_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_number_of_customers DESC

--Total customers by gender
SELECT
	gender,
	COUNT(*) AS total_number_of_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_number_of_customers DESC

--Total products by category
SELECT
	category,
	COUNT(*) AS total_number_of_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_number_of_products DESC

--Average cost in each category
SELECT
	category,
	AVG(cost) AS average_cost_of_category
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost_of_category DESC

--Total revenue generated for each category
SELECT 
	p.category,
	SUM(s.sales_amount) AS revenue_by_category
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY revenue_by_category DESC


--Total revenue generated by each customer
SELECT 
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(s.sales_amount) AS revenue_by_customer
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY revenue_by_customer DESC

--Distribution of sold items across countries
SELECT 
	c.country,
	SUM(s.quantity) AS items_sold_by_country
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY items_sold_by_country DESC